### ISSUE TITLE
No longer builds with libopencv-dev 3.2.0

### ISSUE THREAD

**Issue by rknobbe** [kliment/simarrange#16]
Lots of undefined references, for example:

 `gcc ``pkg-config opencv --libs`` -largtable2 -ladmesh -fopenmp  simarrange.o   -lm -o simarrang
e
simarrange.o: In function `add_stl':
simarrange.c:(.text+0x299): undefined reference to `stl_open'
simarrange.c:(.text+0x2a1): undefined reference to `stl_exit_on_error'
simarrange.c:(.text+0x2a9): undefined reference to `stl_check_facets_exact'
simarrange.c:(.text+0x34c): undefined reference to `stl_translate'
simarrange.c:(.text+0x35a): undefined reference to `cvCreateImage'
simarrange.c:(.text+0x366): undefined reference to `cvSetZero'
simarrange.c:(.text+0x44e): undefined reference to `cvFillConvexPoly'
simarrange.c:(.text+0x4ef): undefined reference to `cvCountNonZero'
simarrange.o: In function `search':
simarrange.c:(.text+0xa14): undefined reference to `cv2DRotationMatrix'
simarrange.c:(.text+0xa5d): undefined reference to `cvWarpAffine'
simarrange.c:(.text+0xae8): undefined reference to `cvResetImageROI'
simarrange.c:(.text+0xb97): undefined reference to `cvSetImageROI'
simarrange.c:(.text+0xbaa): undefined reference to `cvAnd'
simarrange.c:(.text+0xbb4): undefined reference to `cvCountNonZero'
simarrange.c:(.text+0xbcb): undefined reference to `cvCountNonZero'
simarrange.c:(.text+0xbdf): undefined reference to `cvAdd'
`

**Comment by rknobbe** [comment]
Disregard.  Had to rearrange the Makefile 

`
CC=g++

simarrange: simarrange.o
        g++ simarrange.o   `pkg-config opencv --libs` -largtable2 -ladmesh -fopenmp  -lm -o simarrange

`
